julkascript/cardflow

backend/entrypoint.sh

1. Changed the outer double quotes to single quotes in the `if condition` to avoid issues with nested double quotes.
2. Changed the import of the `User` model - since the default User model has been swapped with a custom User model in the `accounts` app which was leading to error ->
``` 
AttributeError: Manager isn't available; 'auth.User' has been swapped for 'accounts.User' 
```
3. Added the email field when creating the super user 
4. Added *email* and *password* fields to be used from the environment variables - I think it is more convinient to use it that way.

Fix issue #14: Superuser not created on container run

---

backend/accounts/serializers.py
backend/accounts/urls.py
backend/accounts/views.py

Added the `username` and `email` fields to the payload of the JWT access token - which looks like this when decoded:
```json
Payload
{
"token_type": "access",
"exp": 1700758582,
"iat": 1700754982,
"jti": "87d5c334749b4bc0a5fea41f6b6daaf8",
"user_id": 2,
"username": "admin2",
"email": "admin2@do.lab"
}
```
>[!NOTE]
>Please let me know if something is not correct or we need to add something else.

Backend/CF-36 Include custom fields username and email in token payload

---

backend/cardflow/settings.py

I have disabled the custom middleware since it is a bit overkill at this moment, while the standard JWT middleware is doing the same work and we can take advantage from the permission classes for controlling the access to the endpoints without excluding them in a list one by one.
It is just commented it in `settings.py` so we can have it for later on, if needed.
Please let me know if this fixes the issue for now, or should I re-thing the logic of the custom middleware and fix it there.

Disabling custom middleware related to fix issue #18

---

backend/listing/filters.py
backend/listing/views.py

This PR fix the need in issue #32 by adding additional query param to the **endpoint : api/listing**
**Example**:
`/api/listing/?card_in_set_id=<number>` -> returns all listings from all users related to the the card in set ID which have *is_listed=true* 
> [!NOTE]
> The QuerySet response returned by this request is configured to return only the listings which are listed for all users. 
*It can be changed to return all visible and unvisible listings and then the front end to filter with additional query param `&is_listed=true`*
For instance if we assume that the card we need to show all currently available listings has   ID:20 the following request to `/api/listing/?card_in_set_id=20` will return below response
``` json
"results": [
{
"id": 2,
"card": 20,
"card_name": "Dark Magician", …
```

Adding search by card_in_set_id query param to the listing endpoint

---

backend/yugioh/filters.py
backend/yugioh/views.py

As requested in issue #35 it is now added to search for a card name in `/api/yugioh/cards_in_set/` endpoint
For example request to `/api/yugioh/cards_in_set/?card_name=Dragon` returns paginated result:
``` json
{
"count": 20,
"next": "http://localhost:8000/api/yugioh/cards_in_set/?card_name=Dragon&page=2",
"previous": null,
"results": [
{
"id": 87,
"yugioh_card": {
"id": 6,
"card_name": "Borreload Dragon",
"type": "Link Monster",
"frame_type": "link",
"description": "3+ Effect Monsters\r\nNeither player can target this card with monster effects. Once per turn (Quick Effect): You can target 1 face-up monster on the field; it loses 500 ATK/DEF. Your opponent cannot activate cards or effects in response to this effect's activation. At the start of the Damage Step, if this card attacks an …
```

Allowing searching in card_in_set endpoint by card_name

---

frontend/src/components/PageHeader.tsx
frontend/src/constants/api.ts
frontend/src/pages/yugioh/SellManagement.tsx
frontend/src/router/Router.tsx
frontend/src/services/yugioh/yugiohService.ts

This PR implements the sell management page, which is entirely functional. There are a few notes, though:
- the pagination differs from the wireframe for consistency with the other pages that use similar tables and to save time
- the "Delist all" and "Deselect all" buttons will perform the respective operations on all listings on the current page, regardless of whether they've been selected or not. The third button opens more options, which includes performing the actions on the selected items. Some of those options are also disabled when appropriate.
- since the branch for CF-20 is not published at the time this PR was opened, I resorted to creating the CRUD service methods I needed in this PR, this may result in a conflict or two (due to this, I've also opted not to include unit tests …

Create sell management page

---

.gitignore
frontend/src/App.tsx
frontend/src/components/auth/AuthForm.tsx
frontend/src/components/navigation/desktop/DesktopLoggedInNav.tsx
frontend/src/components/navigation/mobile/menus/MobileLoggedInNav.tsx
frontend/src/components/navigation/profilePictureAvatar/ProfilePictureAvatar.tsx
frontend/src/components/profile/ProfilePublicData.tsx
frontend/src/components/profile/profileSettings/DeleteAccount.tsx
frontend/src/components/profile/profileSettings/EmailSettings.tsx
frontend/src/components/profile/profileSettings/ShipmentAddressSettings.tsx
frontend/src/components/profile/profileSettings/avatarSettings/AvatarSettings.tsx
frontend/src/components/profile/profileSettings/avatarSettings/handleAvatarUpload.ts
frontend/src/components/profile/profileSettings/usernameSettings/UsernameSettings.tsx
frontend/src/constants/api.ts
frontend/src/context/user.tsx
frontend/src/pages/Home.tsx
frontend/src/pages/profile/ProfilePublicInfoPage.tsx
frontend/src/pages/profile/ProfileSettingsPage.tsx
frontend/src/router/Router.tsx
frontend/src/router/loadPublicUserInfo/loadPublicUserInfo.spec.ts
frontend/src/router/loadPublicUserInfo/loadPublicUserInfo.ts
frontend/src/services/http/http.ts
frontend/src/services/user/types.ts
frontend/src/services/user/user.ts

This PR makes the profile settings page functional; all fields perform the necessary edits/deletions. A bunch of notes:
- when the user changes their username or email, they will be logged out. The reason for this is that their current tokens reflect their old username / email and I figured it'd be more appropriate to have them reauthenticate to receive tokens with up-to-date data. Corresponding texts in the fields have also been changed to reflect that. Let me know if this is not a desired behavior
- the httpService has been updated to handle multipart form data requests.
- the user context and session verification have been updated in this PR; when the user loads the app and has a valid session, the front end will make a request to retrieve the user data as well. This is because some of …

Allow the user to make the changes to their profile on the front end

---

backend/listing/serializers.py

This PR adds detailed information for the card in set for the listing serializer as requested in  PR #50 
Now the listing response is updated as well as the GET shopping cart items endpoint response. 
Both now return everything needed as discussed for example:
```json
{
"count": 1,
"next": null,
"previous": null,
"results": [
{
"id": 9,
"cart_name": "lichice",
"listing": {
"id": 1,
"card": 2,
"card_name": "Dark Magician",
"card_set_id": 2,
"card_in_set": {
"id": 2,
"yugioh_card": {   <-- the card
"id": 1,
"card_name": "Dark Magician",
"type": "Normal Monster",
"frame_type": "normal",
"description": "''The ultimate wizard in terms of attack and defense.''",
"attack": "2500",
"defense": "2100",
"level": "7",
"race": "Spellcaster",
"attribute": "DARK",
"archetype": "Dark Magician",
"image": …
```

Adding card_in_set Field serializer to the listing

---

frontend/src/components/navigation/desktop/buttons/NotificationButton.tsx
frontend/src/components/navigation/mobile/menus/MobileLoggedInNav.tsx
frontend/src/pages/Home.tsx
frontend/src/pages/listing/EditListing.tsx
frontend/src/services/yugioh/yugiohService.ts

This PR addresses issue #52 and also makes the "Start exploring" button in the home page a hyperlink (which links to the search page). What used to be notification hyperlinks now lead to the sell pages. For the link in the mobile menu, the text has also been changed appropriately

Fix issue #52

---

frontend/src/components/BreadcrumbNavigation.tsx
frontend/src/components/PageHeader.tsx
frontend/src/components/sellListing/NewListingTopBar.tsx
frontend/src/pages/Cart.tsx
frontend/src/pages/Search.tsx
frontend/src/pages/yugioh/YugiohCardDetails.tsx

This PR tackles #67 by creating a reusable breadcrumb (which utilizes the one provided by MUI). The component accepts an array of data for each link to make it more flexible and the type for the link data object is also exported so that consumers can define their breadcrumb navigation without cluttering the JSX area of the component significantly.
The breadcrumb also applies colors correctly, with the links having a gray color and the last item (the heading) having a black color.
This PR also introduces a slight change to the ``PageHeader`` component. To be more specific, if ``heading`` is a non-string ReactNode, the component will directly render that instead of rendering it in an ``h1``. The behavior remains unchanged if the heading is a string.
Disclaimer: currently, the "Buy" link …

Create a breadcrumb and fix current issues related to the old one

---

frontend/src/components/navigation/desktop/DesktopLoggedInNav.tsx
frontend/src/components/navigation/mobile/menus/MobileLoggedInNav.tsx
frontend/src/components/navigation/profilePictureAvatar/ProfilePictureAvatar.css
frontend/src/components/navigation/profilePictureAvatar/ProfilePictureAvatar.tsx

This PR addresses #68. Some of the links obviously do not work (and can also be updated if we decide to change them).
Because the dropdown features a logout button, the previous one has been removed from the desktop variant
The mobile menu has also been updated; what used to be the "My profile" link is now a collapsible button that reveals all four links / actions (this includes the logout button which has been moved from its previous location) that can be accessed on the desktop variant. The only relevant difference between the mobile and desktop variants is that the mobile one doesn't feature the email, as I am not sure how I feel about featuring non-clickable elements in it (unless the email part is also supposed to be a hyperlink?).
There are a few minor changes I have gone with that …

Implement user dropdown for profile picture avatar and update mobile menu

---

docker-compose.yml

This PR is targeting issue #73 .
To achieve this task  I have used a simple solution by setting the storage location of the volume to correspond with the `node_modules` directory of the **host**. To do this, a named volume with a local driver and a bind mount has been utilized. 
Synchronizing the `node_modules` folder from the *container* to the *host* is established at creating the container with docker compose. Please note that this action is time consuming and it used around 500sec to be created.
>[!NOTE]
> My suggestions is to delete the current node_modules folder and then start this process because otherwise might not sync as intended.
Please test it and let me know if you approve this approach.

Map the node_modules folder from container to host

---

frontend/src/components/searchField/SearchResultsDisplay.tsx

It's written in the issue that it should be blocked by #65 but it's actually not because sorting out what image will go to the backend is a separate issue. We will always only show one here. Lmk if I missed something.

Show image on camera hover during search

---

frontend/src/components/auth/AuthForm.tsx
frontend/src/components/yugioh/table/YugiohCardDetailsCell.tsx
frontend/src/components/yugioh/table/YugiohCardDetailsTable.tsx
frontend/src/components/yugioh/table/market/AddToCartButton.tsx
frontend/src/components/yugioh/table/market/YugiohCardMarket.tsx
frontend/src/components/yugioh/table/market/YugiohCardMarketTableCell.tsx
frontend/src/components/yugioh/table/market/YugiohCardQuantityField.tsx
frontend/src/index.css
frontend/src/pages/Home.module.css
frontend/src/pages/Home.tsx
frontend/src/pages/NotFound.tsx
frontend/src/pages/yugioh/BestSellers.tsx

This PR is part of my efforts to implement some of the mobile Figma wireframes. This PR focuses on a few basic pages, which have been combined in one PR as the changes are of a trivial nature. [Review the UI](https://imgur.com/a/3DyLlIA)
edit: this also features a super minor change to the best sellers page, which involves just centering the text on mobile.
The login and register pages have also been updated with MUI components.
The not found page has been made to look more like the wireframes (I will admit that, up until recently, I hadn't even known that we had specific wireframes for the page). I have left the home link intact as to provide some convenient escape hatch for the user.
Note to myself: improve client-side validation on login and register pages some other time
Let me know …

Make the home page, register page, login page, card / market details table, and not found page responsive

---

frontend/src/components/yugioh/table/market/YugiohCardMarket.tsx

Tackles #97.
The pagination widget is absent when there are no listings, since it's pointless in that context

Add a special text for when there are no listings

---

backend/cart/tests/test_shopping_cart.py
backend/yugioh/management/commands/img_download.py
backend/yugioh/serializers.py
backend/yugioh/utils.py

This PR fixes issue #65 
I have implemented a manage command which is similar to the seed command for downloading one, staple, or all card images.
This was for analytic purposes, but it's good to have it there, just in case.
The logic for saving the cards is simple and if it's not a good approach please let me know.
It has one util function for downloading and saving a card image in our local media folder. After that, a serializer Mixin returns the local URL for the requested image in every serializer where the card image is needed.

Download and Save images locally

---

frontend/src/components/about/ChangelogList.tsx
frontend/src/constants/changelogArchive.ts
frontend/src/pages/about/Changelog.tsx

Closes #120 
Currently, you need to put the newest version as the first element in the array in order for it to be displayed at the top. Now this is reversed—the newest version is on the bottom and will be rendered first. I could maybe look into creating some sorting function to use the version or date, but I feel like it's a good idea to enforce some order in the array itself for readability.
In addition, I noticed that the bullets do not align consistently if they are of different widths, this PR also fixes this.
Finally, I noticed that React was complaining about a missing key, so I fixed that too
(also, something really minor, but I also made the casing in the 1.2 milestone consistent with the one in 1.0)

Fix issues with the changelog

---

backend/cart/models.py
backend/listing/serializers.py
backend/yugioh/serializers.py
frontend/src/components/shoppingCart/ShoppingCartCheckout.tsx
frontend/src/components/shoppingCart/ShoppingCartSummary.tsx
frontend/src/translations/bg/buy.json

Closes #140 
Closes #139
@RyotaMitaraiWeb I decided that it'd be easier to just make the conversions more precise, instead of reworking the way we save the prices. etc. We may definitely consider this in the future, but for now, I just want to get the product out for public beta testing with fewer bugs.

Make conversions precise, fix shopping cart currency bug

---

frontend/src/components/orders/OrdersTableRow.tsx
frontend/src/components/orders/ordersModal/OrdersModal.spec.tsx
frontend/src/components/orders/ordersModal/OrdersModal.tsx

Closes #129 
(^ assuming the backend counterpart is closed first)
If the date at which a particular table row has been rendered is not 10 days after the date in the last element of the order status history (since the last element contains the date at which the order was placed), the not received radio button for the associated modal is disabled. Few notes:
- the button is always disabled when the status is not "sent" (regardless of whether ten days have passed or not), let me know if this is supposed to be changed
- if the OrdersTableRow component experiences a rerender (e.g. due to a page or language change), "today" will be recalculated, which potentially enables the radio button. I have opted for this approach to create something of a pseudo-polling effect for the user.
- I have not …

Disable "Not received" when ten days haven't passed on the front end

---

frontend/src/components/orders/ordersModal/OrdersModal.tsx
frontend/src/components/orders/ordersModal/layout/OrderModalPurchases.tsx
frontend/src/components/orders/ordersModal/layout/OrdersModalHeader.tsx
frontend/src/components/orders/ordersModal/layout/OrdersModalUsernameLink.tsx
frontend/src/translations/bg/account.json

Closes #132 
This PR does three things:
- changes the order of the layout
- makes the separators on the desktop layout correctly aligned
- separates some of the elements in their own components. This was done to make it easier for me to finish this.
I have kept the previous UI mostly intact (e.g. the feedback section is still centered in the middle of its own part), though there may be some minor changes here and there

Adjust order modal sequence and split off some of  the layout

---

frontend/src/translations/en/common.json

This fix addresses #148.
Changes the placeholder text in search bars from "Type / to search" to "Search"

Issue #148

---

frontend/src/components/sellListing/ListingForm.tsx
frontend/src/services/yugioh/types.ts
frontend/src/services/yugioh/yugiohService.spec.ts
frontend/src/translations/bg/sell.json
frontend/src/translations/en/sell.json

Closes #153 
This PR adds the checkbox from the Figma wireframes in a functional condition. On viewports < 1024px, the checkbox is below the three fields due to there being no room to put it horizontally

Implement trade checkbox on the frontend

---

backend/trade/serializers.py
backend/trade/views.py

This PR implements the backend part of Implement My Trades(issue #156 ).
The ```get_queryset``` was modified to return the ```recipiend``` and ```initiator``` user's objects:
```
{
"count": 25,
"next": "http://127.0.0.1:8000/api/trade/?page=2",
"previous": null,
"results": [
{
"id": 4,
"initiator": {
"id": 3,
"username": "pesho",
"email": "pesho@example.com"
},
"recipient": {
"id": 2,
"username": "simo",
"email": "simo@example.com"
},
"initiator_listing": [
10,
11
],
"recipient_listing": [
2
],
"initiator_cash": 0,
"recipient_cash": 0,
"trade_status": "accepted",
"initiator_decision": "accept",
"recipient_decision": "accept"
},
{
"id": 16,
"initiator": {
"id": 2,
"username": "simo",
"email": "simo@example.com"
},
"recipient": {
"id": 4,
"username": "simo1",
"email": "user@example.com"
}, …
```

Implement My Trades

---

backend/trade/serializers.py
frontend/src/constants/api.ts
frontend/src/services/trade/trade.ts

#175 
This PR does two things:
**Trade API adaptation**
This PR updates the frontend with the changes to the trades API on the backend. In this case, the only real changes here are that the negotiate/accept/reject actions are now PATCH requests and that the counter offer API has been removed entirely (as it was unused). As far as I have seen, the frontend itself handles the different scenarios regarding trade statuses accurately without any additional changes, so if there's something specific that is still not correct (except for #176, which should be handled in a different PR) that I have missed, it should probably be mentioned.
**Cash options regression fix**
#179 introduced a regression that prevented an initiator from specifying a cash option for the recipient and vice-versa, which is …

Adapt the frontend to the changes in trade statuses on the backend + fix regression with cash options

---

frontend/src/pages/trade/TradeDetails.tsx

#177 
This PR isn't particularly big, because system messages were mostly functional on the frontend when they were implemented on the backend. The only missing thing was that accept/negotiate/reject events did not refresh the chat and I felt it would make for a jarring experience if those events didn't update the chat at least.
With that said, though, there are a bunch of issues that I have left out, as they are out of scope for this PR and/or will require some further tweaking on the backend.
1. When a user initiates a trade, a rather empty message is generated (see the first one in the image above). This is because the frontend automatically sends a request to create the trade when the user initiates a trade via the UI. And the reason why I did this early on is because the backend …

Integrate missing features regarding system messages on the frontend

---

frontend/src/components/searchField/SearchResultsDisplay.tsx

Closes #184 
The issue was caused by the fact the results display element did not have a higher ``z-index`` than the breadcrumb navigation (thus the navigation was "covering" that search item). This is an important detail, as the issue was not reproducible on all pages (the only instances of the issue I had stumbled upon were all in pages with that breadcrumb navigation menu).
As far as I have tested, this issue does not affect the mobile variant of the search, so nothing has been touched there.
If there are other pages where this issue occurs, please let me know (I have tested a few pages and have not reproduced the issue since the bugfix commit)

Fix issue with first search item's clickability
